### PR TITLE
Use NextJS environment variables

### PR DESCRIPTION
**Pull request by f4bio**
https://nextjs.org/docs/basic-features/environment-variables

### CODE REVIEW

**Comment by mellet** [comment]
Very nice.

Could you also maybe add a `.env.local.sample`.
That way people can rename that file to override default env vars.
It's content can be the same as the `.env.production` file.

Probably will need to adjust the git ignore to allow the sample file.
And adjust the readme to explain to rename that file to override defaults 🥳

**Comment by f4bio** [comment]
> Very nice.
> 
> Could you also maybe add a `.env.local.sample`.
> That way people can rename that file to override default env vars.
> It's content can be the same as the `.env.production` file.
> Probably will need to adjust the git ignore to allow the sample file.
> And adjust the readme to explain to rename that file to override defaults 🥳

I thought about that too. 
And you're right, usually, one would copy the given `.env.defaults` (or  `.env.local.sample`) to `.env.local` and change the values to fit your needs. 
I hoped [my explanation](https://github.com/mellet/csgonades-client/blob/df3d4a8e82a6d322ba170693c313eb3e587f41cd/README.md) would make clear, how to use it... Guess not... :D 
There are some merge conflicts now anyways, so I'll push an update soon ;)

**Comment by mellet** [comment]
> > Very nice.
> > Could you also maybe add a `.env.local.sample`.
> > That way people can rename that file to override default env vars.
> > It's content can be the same as the `.env.production` file.
> > Probably will need to adjust the git ignore to allow the sample file.
> > And adjust the readme to explain to rename that file to override defaults 🥳
> 
> I thought about that too.
> And you're right, usually, one would copy the given `.env.defaults` (or `.env.local.sample`) to `.env.local` and change the values to fit your needs.
> I hoped [my explanation](https://github.com/mellet/csgonades-client/blob/df3d4a8e82a6d322ba170693c313eb3e587f41cd/README.md) would make clear, how to use it... Guess not... :D
> There are some merge conflicts now anyways, so I'll push an update soon ;)

It's probably fine. It's just usually convention to have a sample file for .env.
Also you got some merge conflicts since I merged your other PR that also touched two of the same files.

**Comment by mellet** [comment]
Once merge conflicts are fixed I'll merge this 👍 🚢

**Pull request closed without merging**
